services:
  mysql:
    image: mysql:8.0
    container_name: wave-games-backend-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root         # required
      MYSQL_DATABASE: wave-games-database
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
